{% set name = "motifcluster" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a105bf6ee1decb09c332b98c3abbc89f40c3e8e9ab3f9e6740647b7692acfe6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - networkx >=2.4
    - numpy >=1.18.3
    - python >={{ python_min }}
    - scikit-learn >=0.22.2
    - scipy >=1.4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - motifcluster

about:
  home: https://github.com/WGUNDERWOOD/motifcluster
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Motif-Based Spectral Clustering of Weighted Directed Networks
  doc_url: https://motifcluster.readthedocs.io
  dev_url: https://github.com/WGUNDERWOOD/motifcluster

extra:
  recipe-maintainers:
    - WGUNDERWOOD
